name: Crowdin Action

on:
  push:
    paths: ["public/locales/**"]
    branches: [main]

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: true
          download_translations: false
        env:
          CROWDIN_PROJECT_ID: 714759
          CROWDIN_PERSONAL_TOKEN: "9a75bc9cfc97181940f598d540f1af5b927ae418535d81615eac7d0d096a68cd3f757c7c7c06201d"
